version: '13.0.0#{build}'

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test:ci

build_script:
  - node --version
  - yarn --version
  - yarn test:ci
  - yarn build
  - yarn build:bo

cache:
  - node_modules