version: '20.0.0#{build}'

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test:ci

build_script:
  - node --version
  - yarn --version
  - yarn test:ci
  - yarn build
  - yarn build:no-bo
  - yarn build:no-service-worker

cache:
  - node_modules