version: '12.0.0#{build}'

environment:
  matrix:
    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node 6.11.1
  - npm install -g yarn
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test:ci

build_script:
  - node --version
  - yarn --version
  - yarn test:ci
  - yarn build
  - yarn build:bo
  - yarn build:cc
  - yarn build:no-aot


cache:
  - node_modules