sudo: false
env:
  - CXX=g++-4.8 CI=true
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

install: npm install yarn -g && yarn install

# We need to test all potentially used production build version to ensure that none of them fails,
# and to get a proper output if any of them does.
script:
  - yarn test:ci
  - yarn build
  - yarn build:no-bo
  - yarn build:no-service-worker

